// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.14.0
// source: sqlproto/sqlproto.proto

package sqlproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CRUDOperation int32

const (
	CRUDOperation_UNKNOWN CRUDOperation = 0
	CRUDOperation_CREATE  CRUDOperation = 1
	CRUDOperation_READ    CRUDOperation = 2
	CRUDOperation_UPDATE  CRUDOperation = 3
	CRUDOperation_DELETE  CRUDOperation = 4
)

// Enum value maps for CRUDOperation.
var (
	CRUDOperation_name = map[int32]string{
		0: "UNKNOWN",
		1: "CREATE",
		2: "READ",
		3: "UPDATE",
		4: "DELETE",
	}
	CRUDOperation_value = map[string]int32{
		"UNKNOWN": 0,
		"CREATE":  1,
		"READ":    2,
		"UPDATE":  3,
		"DELETE":  4,
	}
)

func (x CRUDOperation) Enum() *CRUDOperation {
	p := new(CRUDOperation)
	*p = x
	return p
}

func (x CRUDOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CRUDOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_sqlproto_sqlproto_proto_enumTypes[0].Descriptor()
}

func (CRUDOperation) Type() protoreflect.EnumType {
	return &file_sqlproto_sqlproto_proto_enumTypes[0]
}

func (x CRUDOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CRUDOperation.Descriptor instead.
func (CRUDOperation) EnumDescriptor() ([]byte, []int) {
	return file_sqlproto_sqlproto_proto_rawDescGZIP(), []int{0}
}

var File_sqlproto_sqlproto_proto protoreflect.FileDescriptor

var file_sqlproto_sqlproto_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x71, 0x6c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x71, 0x6c, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x71, 0x6c, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2a, 0x4a, 0x0a, 0x0d, 0x43, 0x52, 0x55, 0x44, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x08, 0x0a,
	0x04, 0x52, 0x45, 0x41, 0x44, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50, 0x44, 0x41, 0x54,
	0x45, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x04, 0x42,
	0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x73, 0x71, 0x6c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sqlproto_sqlproto_proto_rawDescOnce sync.Once
	file_sqlproto_sqlproto_proto_rawDescData = file_sqlproto_sqlproto_proto_rawDesc
)

func file_sqlproto_sqlproto_proto_rawDescGZIP() []byte {
	file_sqlproto_sqlproto_proto_rawDescOnce.Do(func() {
		file_sqlproto_sqlproto_proto_rawDescData = protoimpl.X.CompressGZIP(file_sqlproto_sqlproto_proto_rawDescData)
	})
	return file_sqlproto_sqlproto_proto_rawDescData
}

var file_sqlproto_sqlproto_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sqlproto_sqlproto_proto_goTypes = []interface{}{
	(CRUDOperation)(0), // 0: sqlproto.CRUDOperation
}
var file_sqlproto_sqlproto_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sqlproto_sqlproto_proto_init() }
func file_sqlproto_sqlproto_proto_init() {
	if File_sqlproto_sqlproto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sqlproto_sqlproto_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sqlproto_sqlproto_proto_goTypes,
		DependencyIndexes: file_sqlproto_sqlproto_proto_depIdxs,
		EnumInfos:         file_sqlproto_sqlproto_proto_enumTypes,
	}.Build()
	File_sqlproto_sqlproto_proto = out.File
	file_sqlproto_sqlproto_proto_rawDesc = nil
	file_sqlproto_sqlproto_proto_goTypes = nil
	file_sqlproto_sqlproto_proto_depIdxs = nil
}
